### ISSUE TITLE
i have tildes in my asterisks

### ISSUE THREAD

**Issue by eee-dev** [relative/mirage#7]
~* are broken via coronavirus!!!

**Comment by relative** [comment]
ok

**Comment by eee-dev** [comment]
you must fix this

**Comment by relative** [comment]
fix what

**Comment by eee-dev** [comment]
tildes in the asterisks

**Comment by eee-dev** [comment]
they confuse emacs

**Comment by relative** [comment]
> tildes in the asterisks

https://www.computerhope.com/jargon/b/backspac.htm

**Comment by eee-dev** [comment]
does emacs support it???

**Comment by eee-dev** [comment]
i must get the coronavirus!!!

**Comment by eee-dev** [comment]
@relative her majesty must give the emacs god a bible for safekeeping

**Comment by relative** [comment]
u good

**Comment by eee-dev** [comment]
i have experienced an error!!!

**Comment by relative** [comment]
> i have experienced an error!!!

whats your error

**Comment by eee-dev** [comment]
baby wogue do it like that
https://www.youtube.com/watch?v=OoUVSHDbAeM
![](https://i.ytimg.com/an_webp/OoUVSHDbAeM/mqdefault_6s.webp?du=3000&sqp=CIXlmfQF&rs=AOn4CLAs27PktA_K38Sukf9Z7RhQApJtFw)

**Comment by relative** [comment]
> baby wogue do it like that
> https://www.youtube.com/watch?v=OoUVSHDbAeM
> ![](https://camo.githubusercontent.com/57108ddfcf8ff49ae9b3bd384b1a4a5760638d16/68747470733a2f2f692e7974696d672e636f6d2f616e5f776562702f4f6f55565348446241654d2f6d7164656661756c745f36732e776562703f64753d33303030267371703d4349586c6d6651462672733d414f6e34434c41733237506b74415f4b333853756b66395a3752685141704a744677)

dou.bt.it/doubt.png

**Comment by eee-dev** [comment]
> 
> 
> > i have experienced an error!!!
> 
> whats your error
you may be smoking BUT EMACS IS ATERISKS <!DOCTYPE html>





<html class="no-js" lang="en_US">

<head>
	<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta http-equiv="content-type" content="text/html; charset=UTF-8;charset=utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=1" />
<meta name="HandheldFriendly" content="true"/>

<link rel="canonical" href="https://duckduckgo.com/">

<link rel="stylesheet" href="/s1884.css" type="text/css">

<link rel="stylesheet" href="/o1884.css" type="text/css">



<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
<link rel="apple-touch-icon" href="/assets/icons/meta/DDG-iOS-icon_60x60.png"/>
<link rel="apple-touch-icon" sizes="76x76" href="/assets/icons/meta/DDG-iOS-icon_76x76.png"/>
<link rel="apple-touch-icon" sizes="120x120" href="/assets/icons/meta/DDG-iOS-icon_120x120.png"/>
<link rel="apple-touch-icon" sizes="152x152" href="/assets/icons/meta/DDG-iOS-icon_152x152.png"/>
<link rel="image_src" href="/assets/icons/meta/DDG-icon_256x256.png"/>
<link rel="manifest" href="/manifest.json"/>

<meta name="twitter:card" content="summary">
<meta name="twitter:site" value="@duckduckgo">

<meta property="og:url" content="https://duckduckgo.com/" />
<meta property="og:site_name" content="DuckDuckGo" />
<meta property="og:image" content="https://duckduckgo.com/assets/logo_social-media.png">


	<title>DuckDuckGo — Privacy, simplified.</title>
<meta property="og:title" content="DuckDuckGo — Privacy, simplified." />


<meta property="og:description" content="The Internet privacy company that empowers you to seamlessly take control of your personal information online, without any tradeoffs.">
<meta name="description" content="The Internet privacy company that empowers you to seamlessly take control of your personal information online, without any tradeoffs.">


</head>
<body id="pg-index" class="page-index body--home">
	<script type="text/javascript">
var settings_js_version = "/s2475.js",
    locale = "en_US";
</script>
<script type="text/javascript" src="/lib/l113.js"></script>
<script type="text/javascript" src="/locale/en_US/duckduckgo14.js"></script>
<script type="text/javascript" src="/util/u435.js"></script>
<script type="text/javascript" src="/d2772.js"></script>



<script type="text/javascript">
    DDG.page = new DDG.Pages.Home();
</script>



	<div class="site-wrapper  site-wrapper--home  js-site-wrapper">
	
		
			<div class="header-wrap--home  js-header-wrap">
	<div class="header--aside js-header-aside"></div>
</div>
			<div id="" class="content-wrap--home">
				<div id="content_homepage" class="content--home" style="visibility: hidden">
					<div class="cw--c">
								<div class="logo-wrap--home">
			<a id="logo_homepage_link" class="logo_homepage" href="/about">
				About DuckDuckGo
				<span class="logo_homepage__tt">Duck it!</span>
			</a>
		</div>

						<div class="search-wrap--home">
									<form id="search_form_homepage" class="search  search--home  js-search-form" name="x" method="POST" action="/html">
			<input id="search_form_input_homepage" class="search__input  js-search-input" type="text" autocomplete="off" name="q" tabindex="1" value="">
			<input id="search_button_homepage" class="search__button  js-search-button" type="submit" tabindex="2" value="S" />
			<input id="search_form_input_clear" class="search__clear  empty  js-search-clear" type="button" tabindex="3" value="X" />
			<div id="search_elements_hidden" class="search__hidden  js-search-hidden"></div>
		</form>

						</div>
		
	

						
<noscript>
    <div class="tag-home">
        <div class="tag-home__wrapper">
            <div class="tag-home__item">
                The search engine that doesn't track you.
                <span class="hide--screen-xs"><a href="/about" class="tag-home__link">Learn More</a>.</span>
            </div>
        </div>
    </div>
</noscript>
<div class="tag-home  tag-home--slide  no-js__hide  js-tag-home"></div>
        <div id="error_homepage"></div>


	
		
					</div> 
				</div> 
			</div> 
			<div id="footer_homepage" class="foot-home  js-foot-home"></div>

<script type="text/javascript">
	{function seterr(str) {
		var error=document.getElementById('error_homepage');
		error.innerHTML=str;
		$(error).css('display','block');
	}
	var err=new RegExp('[\?\&]e=([^\&]+)');var errm=new Array();errm['2']='no search';errm['3']='search too long';errm['4']='not UTF\u002d8 encoding';errm['6']='too many search terms';if (err.test(window.location.href)) seterr('Oops, '+(errm[RegExp.$1]?errm[RegExp.$1]:'there was an error.')+' &nbsp;Please try again');};
	
	if (kurl) {
	  document.getElementById("logo_homepage_link").href += (document.getElementById("logo_homepage_link").href.indexOf('?')==-1 ? '?t=i' : '') + kurl;
	}
</script>

		
	
	</div> 
</body>
</html>

**Comment by relative** [comment]
come to our discord i'd like to talk to you https://mirage.photos/discord

**Comment by eee-dev** [comment]
!!! html is a progr**_amming language buddy_**

**Comment by eee-dev** [comment]
But how to use HTML to activate web browser?

**Comment by relative** [comment]
come to our discord i'd like to talk to you https://mirage.photos/discord

**Comment by eee-dev** [comment]
i cannot get into mirage.photos and u r asking me to join shady discord???

**Comment by eee-dev** [comment]
i cannot find how to html this

**Comment by relative** [comment]
ok when you're ready to talk about it come to the discord

**Comment by eee-dev** [comment]
i cannot use mirgae photos, i need support please @relative

**Comment by eee-dev** [comment]
i wish u would give support u are trying to waste my time with not tell me solution?

**Comment by relative** [comment]
ok whats ur username

**Comment by eee-dev** [comment]
??? eee-dev

**Comment by eee-dev** [comment]
https://github.com/eee-dev

**Comment by eee-dev** [comment]
AGAIN EMACS WILL NOT OPEN HTML MIRAGE.PHOTOS? browser is not doing it!! chrome bug???

**Comment by relative** [comment]
i don't quite see the problem here

**Comment by eee-dev** [comment]
ur website is not working for me?

**Comment by eee-dev** [comment]
i will ask contact me on https://github.com/eee-dev right now

**Comment by relative** [comment]
> ur website is not working for me?

working for me, try https://mirage.photos/oldindex

**Comment by eee-dev** [comment]
> 
> 
> > ur website is not working for me?
> 
> working for me, try https://mirage.photos/oldindex
virus scannar says it a virus! should disabel it?

**Comment by relative** [comment]
> > > ur website is not working for me?
> > 
> > 
> > working for me, try https://mirage.photos/oldindex
> > virus scannar says it a virus! should disabel it?

not sure what to say about that sorry boss

**Comment by eee-dev** [comment]
> 
> 
> > > > ur website is not working for me?
> > > 
> > > 
> > > working for me, try https://mirage.photos/oldindex
> > > virus scannar says it a virus! should disabel it?
> 
> not sure what to say about that sorry boss

tht is confusig. i will disabel it, give me a second sir

**Comment by relative** [comment]
> > > > > ur website is not working for me?
> > > > 
> > > > 
> > > > working for me, try https://mirage.photos/oldindex
> > > > virus scannar says it a virus! should disabel it?
> > 
> > 
> > not sure what to say about that sorry boss
> 
> tht is confusig. i will disabel it, give me a second sir

ok

**Comment by NotII** [comment]
English 100

**Comment by relative** [comment]
hey whyd u stop responding @eee-dev

**Comment by eee-dev** [comment]
??? busy fix html

**Comment by eee-dev** [comment]
i disabel anti virus scannar so it work?

**Comment by eee-dev** [comment]
> English 100

i am sorry sir english will learning

**Comment by eee-dev** [comment]
i see why this break...... 
sir ur sire is down

**Comment by relative** [comment]
> > English 100
> 
> i am sorry sir english will learning

CAN U TAKE A LOOK AT THIS PLEASE SIR https://mirage.photos/500

**Comment by resynth1943** [comment]
it say dns is not able! yur site is bug for me

**Comment by resynth1943** [comment]
Why are you sending this in the Telegram eee-dev

**Comment by relative** [comment]
anyways this was fun @resynth1943,
@eee-dev I stopped it u can get off ur mobile

**Comment by resynth1943** [comment]
Shrug sure
![5NkHYB2](https://user-images.githubusercontent.com/49915996/78318514-d3dae300-755c-11ea-826d-f665eb18c782.png)
